
/* !!! This is code generated by Prisma. Do not edit directly. !!!
/* eslint-disable */
// biome-ignore-all lint: generated file

Object.defineProperty(exports, "__esModule", { value: true });

const {
  PrismaClientKnownRequestError,
  PrismaClientUnknownRequestError,
  PrismaClientRustPanicError,
  PrismaClientInitializationError,
  PrismaClientValidationError,
  getPrismaClient,
  sqltag,
  empty,
  join,
  raw,
  skip,
  Decimal,
  Debug,
  DbNull,
  JsonNull,
  AnyNull,
  NullTypes,
  makeStrictEnum,
  Extensions,
  warnOnce,
  defineDmmfProperty,
  Public,
  getRuntime,
  createParam,
} = require('./runtime/client.js')


const Prisma = {}

exports.Prisma = Prisma
exports.$Enums = {}

/**
 * Prisma Client JS version: 7.3.0
 * Query Engine version: 9d6ad21cbbceab97458517b147a6a09ff43aa735
 */
Prisma.prismaVersion = {
  client: "7.3.0",
  engine: "9d6ad21cbbceab97458517b147a6a09ff43aa735"
}

Prisma.PrismaClientKnownRequestError = PrismaClientKnownRequestError;
Prisma.PrismaClientUnknownRequestError = PrismaClientUnknownRequestError
Prisma.PrismaClientRustPanicError = PrismaClientRustPanicError
Prisma.PrismaClientInitializationError = PrismaClientInitializationError
Prisma.PrismaClientValidationError = PrismaClientValidationError
Prisma.Decimal = Decimal

/**
 * Re-export of sql-template-tag
 */
Prisma.sql = sqltag
Prisma.empty = empty
Prisma.join = join
Prisma.raw = raw
Prisma.validator = Public.validator

/**
* Extensions
*/
Prisma.getExtensionContext = Extensions.getExtensionContext
Prisma.defineExtension = Extensions.defineExtension

/**
 * Shorthand utilities for JSON filtering
 */
Prisma.DbNull = DbNull
Prisma.JsonNull = JsonNull
Prisma.AnyNull = AnyNull

Prisma.NullTypes = NullTypes




  const path = require('path')

/**
 * Enums
 */
exports.Prisma.TransactionIsolationLevel = makeStrictEnum({
  Serializable: 'Serializable'
});

exports.Prisma.EmployeeScalarFieldEnum = {
  id: 'id',
  name: 'name',
  email: 'email',
  phone: 'phone',
  idType: 'idType',
  idNumber: 'idNumber',
  stateOfOrigin: 'stateOfOrigin',
  hasPassport: 'hasPassport',
  hasCredentials: 'hasCredentials',
  role: 'role',
  dept: 'dept',
  type: 'type',
  salary: 'salary',
  pfa: 'pfa',
  rsa: 'rsa',
  hmo: 'hmo',
  bloodGroup: 'bloodGroup',
  medicalCond: 'medicalCond',
  proofOfLife: 'proofOfLife',
  uniqueTrait: 'uniqueTrait',
  bank: 'bank',
  accountNo: 'accountNo',
  bvn: 'bvn',
  nokName: 'nokName',
  nokPhone: 'nokPhone',
  status: 'status',
  image: 'image',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
};

exports.Prisma.SortOrder = {
  asc: 'asc',
  desc: 'desc'
};

exports.Prisma.NullsOrder = {
  first: 'first',
  last: 'last'
};


exports.Prisma.ModelName = {
  Employee: 'Employee'
};
/**
 * Create the Client
 */
const config = {
  "previewFeatures": [],
  "clientVersion": "7.3.0",
  "engineVersion": "9d6ad21cbbceab97458517b147a6a09ff43aa735",
  "activeProvider": "sqlite",
  "inlineSchema": "// This is your Prisma schema file,\n// learn more about it in the docs: https://pris.ly/d/prisma-schema\n\ngenerator client {\n  provider = \"prisma-client-js\"\n  output   = \"./generated-client\"\n}\n\ndatasource db {\n  provider = \"sqlite\"\n}\n\nmodel Employee {\n  id             Int      @id @default(autoincrement())\n  name           String\n  email          String   @unique\n  phone          String\n  idType         String\n  idNumber       String\n  stateOfOrigin  String\n  hasPassport    Boolean  @default(false)\n  hasCredentials Boolean  @default(false)\n  role           String\n  dept           String\n  type           String   @default(\"Full-Time\")\n  salary         String\n  pfa            String?\n  rsa            String?\n  hmo            String?\n  bloodGroup     String?\n  medicalCond    String?\n  proofOfLife    String?\n  uniqueTrait    String?\n  bank           String?\n  accountNo      String?\n  bvn            String?\n  nokName        String?\n  nokPhone       String?\n  status         String   @default(\"Active\")\n  image          String?\n  createdAt      DateTime @default(now())\n  updatedAt      DateTime @updatedAt\n}\n"
}

config.runtimeDataModel = JSON.parse("{\"models\":{\"Employee\":{\"fields\":[{\"name\":\"id\",\"kind\":\"scalar\",\"type\":\"Int\"},{\"name\":\"name\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"email\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"phone\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"idType\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"idNumber\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"stateOfOrigin\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"hasPassport\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"hasCredentials\",\"kind\":\"scalar\",\"type\":\"Boolean\"},{\"name\":\"role\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"dept\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"type\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"salary\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"pfa\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"rsa\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"hmo\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"bloodGroup\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"medicalCond\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"proofOfLife\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"uniqueTrait\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"bank\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"accountNo\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"bvn\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"nokName\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"nokPhone\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"status\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"image\",\"kind\":\"scalar\",\"type\":\"String\"},{\"name\":\"createdAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"},{\"name\":\"updatedAt\",\"kind\":\"scalar\",\"type\":\"DateTime\"}],\"dbName\":null}},\"enums\":{},\"types\":{}}")
defineDmmfProperty(exports.Prisma, config.runtimeDataModel)
config.compilerWasm = {
      getRuntime: async () => require('./query_compiler_fast_bg.js'),
      getQueryCompilerWasmModule: async () => {
        const { Buffer } = require('node:buffer')
        const { wasm } = require('./query_compiler_fast_bg.wasm-base64.js')
        const queryCompilerWasmFileBytes = Buffer.from(wasm, 'base64')

        return new WebAssembly.Module(queryCompilerWasmFileBytes)
      },
      importName: './query_compiler_fast_bg.js',
    }

const PrismaClient = getPrismaClient(config)
exports.PrismaClient = PrismaClient
Object.assign(exports, Prisma)
